Repository ripe-tech/ripe-id-api-js, pull requests merged in 2022-05, with the labels that each got.

#13 #265 Add `createAccountMultipart`
  CHANGELOG.md
  js/account.js
Labels: enhancement

#14 Version: 0.7.2
  CHANGELOG.md
  package.json
Labels: release 🎉

#15 fix: `eslint-config-hive` transitive dependencies problem for `npm`
  CHANGELOG.md
  package.json
Labels: bug, back-port 🔮
